# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-09-14 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 18, 19, 64794, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 18, 19, 65179, tzinfo=utc)),
        ),
    ]
